# Generated by Django 3.0 on 2020-06-24 08:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('chinese', '汉语'), ('english', '英语'), ('french', '法语')], max_length=22, null=True, verbose_name='使用语言'),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('1', '启用'), ('0', '禁用')], default='1', max_length=200, verbose_name='状态'),
        ),
    ]
