# Generated by Django 3.0 on 2020-06-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200624_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='headImg',
            field=models.FileField(default='', upload_to='./upload/'),
        ),
    ]
