# Generated by Django 3.0 on 2020-06-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_headimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='headImg',
            field=models.ImageField(default='', upload_to='polls/%Y/%m/%d/'),
        ),
    ]
